spring:
  datasource:
    url: jdbc:h2:tcp://localhost/../../h2-db-server/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false # OSIV off
# OSIC off :
  # - 모든 지연 로딩 로직을 트랜잭션 안에서 구현 하거나 fetch join을 사용

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace